# Generated by Django 5.1.4 on 2024-12-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="status",
        ),
        migrations.AddField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(through="Notio.NoteTag", to="Notio.tag"),
        ),
    ]
